version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    #These 2 lines allow us to use an interactive terminal (e.g. input enabled)
    stdin_open: true
    tty: true

    container_name: gp-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    # Optional: if your app needs environment variables for DB connection
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example

    command: >
      sh -c "printf '0\n' |
             java -jar SET08103--Friday-4PM-Group-8-0.1.0.1-jar-with-dependencies.jar"

  db:
    build: ./db
    container_name: gp-db
    restart: always
    ports:
      - "33060:3306"

  app-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example